name: 'Pentest-Tools.com Scan Action'
description: 'The Pentest-Tools.com Scan Action'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  target:
    description: 'The target you want to scan'
    required: true
  key:
    description: 'Your PTT key. If you leave this empty, you can only do free light scans'
    required: false
  format:
    description: 'The format you want the report in'
    required: false
    default: text
  fail:
    description: 'Fail the action in case we found at least this vulnerability risk'
    required: false
    default: none
  type:
    description: 'Scan type. It has the same meaning as in the Pentest-Tools.com platform. Possible values: light, deep'
    required: false
    default: light
outputs:
  result:
    description: 'The full report from `ptt`'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PTT_QUIET: 1
    PTT_FORMAT: ${{ inputs.format }}
    PTT_KEY: ${{ inputs.key }}
    PTT_TARGET: ${{ inputs.target }}
    PTT_FAIL: ${{ inputs.fail }}
    PTT_SCAN_TYPE: ${{ inputs.type }}
  args:
    - run
    - website_scanner
