on:
  push:
  workflow_dispatch:
    inputs:
      pr-id:
        type: string
        description: PR ID
        required: true

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test that our Github Action works
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Actual test
        uses: ./ # Uses an action in the root directory
        id: ptt
        with:
          target: 'https://pentest-ground.com:81'
          format: text
      # Use the output
      - name: Check the output
        run: echo "The report ${{ steps.ptt.outputs.result }}"

  test_published_action:
    name: Test that our published Github Action works
    runs-on: ubuntu-latest
    steps:
      - name: Actual test
        uses: pentesttoolscom/pentesttools-github-action@master
        id: ptt
        with:
          target: example.com # Has to be accessible to our scanners: https://pentest-tools.com/whitelist-ipv4.txt
      - name: Print the output
        run: echo "The report ${{ steps.ptt.outputs.result }}"
  test_that_action_fails:
    runs-on: ubuntu-latest
    name: Test that our Github Action fails when it needs to fail
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Actual test
        uses: ./ # Uses an action in the root directory
        id: ptt
        with:
          # No target, which is a required parameter
          target:
          format: text
      # Use the output
      - name: Check the output
        run: echo "The report ${{ steps.ptt.outputs.result }}"

  test_that_action_fails_if_fail_criteria:
    runs-on: ubuntu-latest
    name: Test that our Github Action fails when it needs to fail
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Actual test
        uses: ./ # Uses an action in the root directory
        id: ptt
        with:
          target: pentest-ground.com:81
          format: text
          fail: low
      # Use the output
      - name: Check the output
        run: echo "The report ${{ steps.ptt.outputs.result }}"

  test_manual_workflow:
    runs-on: ubuntu-latest
    name: Test that our Github Action runs manually
    if: github.event_name == 'workflow_dispatch'
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Actual test
        uses: ./ # Uses an action in the root directory
        id: ptt
        with:
          target: pentest-ground.com:81
          format: text
          fail: low
      # Use the output
      - name: Check the output
        run: echo "The report ${{ steps.ptt.outputs.result }}"
